GET http://localhost:8000/api/sourcing/recherche

###

GET http://localhost:8000/api/villes?nom=amiens


###

GET http://localhost:8000/api/get_cv/2


###

POST http://localhost:8000/api/post_cv
Content-Type: application/json

{
    "name": "",
    "owner": ""
}


###

GET http://localhost:8000/api/metiers?libelle=web